"""government corpus tables

Revision ID: 071d6d1a648a
Revises: 701cd10a91d5
Create Date: 2026-06-22 15:25:36.972042
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

revision: str = '071d6d1a648a'
down_revision: str | None = '701cd10a91d5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_documents',
    sa.Column('authority', sa.String(length=32), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=40), nullable=False),
    sa.Column('citation_label', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('raw_uri', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['corpus_documents.id'], name=op.f('fk_corpus_documents_supersedes_id_corpus_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_documents')),
    sa.UniqueConstraint('authority', 'external_id', 'version_label', name=op.f('uq_corpus_documents_authority'))
    )
    op.create_index(op.f('ix_corpus_documents_content_hash'), 'corpus_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_corpus_documents_external_id'), 'corpus_documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_corpus_documents_is_current'), 'corpus_documents', ['is_current'], unique=False)
    op.create_table('corpus_chunks',
    sa.Column('corpus_document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=255), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('jurisdiction', sa.String(length=40), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['corpus_document_id'], ['corpus_documents.id'], name=op.f('fk_corpus_chunks_corpus_document_id_corpus_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corpus_chunks')),
    sa.UniqueConstraint('corpus_document_id', 'ordinal', name=op.f('uq_corpus_chunks_corpus_document_id'))
    )
    op.create_index(op.f('ix_corpus_chunks_corpus_document_id'), 'corpus_chunks', ['corpus_document_id'], unique=False)
    op.create_index(op.f('ix_corpus_chunks_doc_type'), 'corpus_chunks', ['doc_type'], unique=False)
    op.create_index('ix_corpus_chunks_embedding_current', 'corpus_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('is_current'))
    op.create_index(op.f('ix_corpus_chunks_is_current'), 'corpus_chunks', ['is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corpus_chunks_is_current'), table_name='corpus_chunks')
    op.drop_index('ix_corpus_chunks_embedding_current', table_name='corpus_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_corpus_chunks_doc_type'), table_name='corpus_chunks')
    op.drop_index(op.f('ix_corpus_chunks_corpus_document_id'), table_name='corpus_chunks')
    op.drop_table('corpus_chunks')
    op.drop_index(op.f('ix_corpus_documents_is_current'), table_name='corpus_documents')
    op.drop_index(op.f('ix_corpus_documents_external_id'), table_name='corpus_documents')
    op.drop_index(op.f('ix_corpus_documents_content_hash'), table_name='corpus_documents')
    op.drop_table('corpus_documents')
    # ### end Alembic commands ###
