"""obligations renewals engine

Revision ID: 701cd10a91d5
Revises: bce9faaba33b
Create Date: 2026-06-22 10:25:07.278500
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '701cd10a91d5'
down_revision: str | None = 'bce9faaba33b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obligations',
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('recurrence', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('notify_lead_days', sa.Integer(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_obligations_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligations')),
    sa.UniqueConstraint('org_id', 'kind', 'title', name=op.f('uq_obligations_org_id'))
    )
    op.create_index(op.f('ix_obligations_org_id'), 'obligations', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_org_id'), table_name='obligations')
    op.drop_table('obligations')
    # ### end Alembic commands ###
