"""spend guardrail rules + phone + auth category

Revision ID: 845eb2b07ead
Revises: adbc8413f4e2
Create Date: 2026-06-30 21:02:03.729811
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '845eb2b07ead'
down_revision: str | None = 'adbc8413f4e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_merchant_rules',
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('match_value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_spend_merchant_rules_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spend_merchant_rules')),
    sa.UniqueConstraint('org_id', 'kind', 'match_type', 'match_value', name=op.f('uq_spend_merchant_rules_org_id'))
    )
    op.create_index(op.f('ix_spend_merchant_rules_kind'), 'spend_merchant_rules', ['kind'], unique=False)
    op.create_index(op.f('ix_spend_merchant_rules_match_value'), 'spend_merchant_rules', ['match_value'], unique=False)
    op.create_index(op.f('ix_spend_merchant_rules_org_id'), 'spend_merchant_rules', ['org_id'], unique=False)
    op.add_column('cardholders', sa.Column('phone', sa.String(length=32), nullable=True))
    op.add_column('spend_authorizations', sa.Column('category', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_spend_authorizations_category'), 'spend_authorizations', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spend_authorizations_category'), table_name='spend_authorizations')
    op.drop_column('spend_authorizations', 'category')
    op.drop_column('cardholders', 'phone')
    op.drop_index(op.f('ix_spend_merchant_rules_org_id'), table_name='spend_merchant_rules')
    op.drop_index(op.f('ix_spend_merchant_rules_match_value'), table_name='spend_merchant_rules')
    op.drop_index(op.f('ix_spend_merchant_rules_kind'), table_name='spend_merchant_rules')
    op.drop_table('spend_merchant_rules')
    # ### end Alembic commands ###
