"""spend guardrail + entitlements

Revision ID: adbc8413f4e2
Revises: 071d6d1a648a
Create Date: 2026-06-30 20:43:47.823312
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'adbc8413f4e2'
down_revision: str | None = '071d6d1a648a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardholders',
    sa.Column('stripe_cardholder_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cardholders_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cardholders')),
    sa.UniqueConstraint('stripe_cardholder_id', name=op.f('uq_cardholders_stripe_cardholder_id'))
    )
    op.create_index(op.f('ix_cardholders_org_id'), 'cardholders', ['org_id'], unique=False)
    op.create_index(op.f('ix_cardholders_stripe_cardholder_id'), 'cardholders', ['stripe_cardholder_id'], unique=False)
    op.create_table('entitlements',
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_entitlements_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlements')),
    sa.UniqueConstraint('org_id', name=op.f('uq_entitlements_org_id'))
    )
    op.create_index(op.f('ix_entitlements_org_id'), 'entitlements', ['org_id'], unique=False)
    op.create_index(op.f('ix_entitlements_stripe_subscription_id'), 'entitlements', ['stripe_subscription_id'], unique=False)
    op.create_table('spend_budgets',
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('mcc', sa.String(length=4), nullable=True),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('limit_cents', sa.Integer(), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_spend_budgets_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spend_budgets'))
    )
    op.create_index(op.f('ix_spend_budgets_category'), 'spend_budgets', ['category'], unique=False)
    op.create_index(op.f('ix_spend_budgets_mcc'), 'spend_budgets', ['mcc'], unique=False)
    op.create_index(op.f('ix_spend_budgets_merchant'), 'spend_budgets', ['merchant'], unique=False)
    op.create_index(op.f('ix_spend_budgets_org_id'), 'spend_budgets', ['org_id'], unique=False)
    op.create_table('cards',
    sa.Column('stripe_card_id', sa.String(length=255), nullable=True),
    sa.Column('cardholder_id', sa.UUID(), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('spending_profile_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cardholder_id'], ['cardholders.id'], name=op.f('fk_cards_cardholder_id_cardholders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_cards_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cards')),
    sa.UniqueConstraint('stripe_card_id', name=op.f('uq_cards_stripe_card_id'))
    )
    op.create_index(op.f('ix_cards_cardholder_id'), 'cards', ['cardholder_id'], unique=False)
    op.create_index(op.f('ix_cards_org_id'), 'cards', ['org_id'], unique=False)
    op.create_index(op.f('ix_cards_stripe_card_id'), 'cards', ['stripe_card_id'], unique=False)
    op.create_table('spend_authorizations',
    sa.Column('stripe_auth_id', sa.String(length=255), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('mcc', sa.String(length=4), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_spend_authorizations_card_id_cards'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_spend_authorizations_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spend_authorizations')),
    sa.UniqueConstraint('stripe_auth_id', name=op.f('uq_spend_authorizations_stripe_auth_id'))
    )
    op.create_index(op.f('ix_spend_authorizations_card_id'), 'spend_authorizations', ['card_id'], unique=False)
    op.create_index(op.f('ix_spend_authorizations_org_id'), 'spend_authorizations', ['org_id'], unique=False)
    op.create_index(op.f('ix_spend_authorizations_stripe_auth_id'), 'spend_authorizations', ['stripe_auth_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spend_authorizations_stripe_auth_id'), table_name='spend_authorizations')
    op.drop_index(op.f('ix_spend_authorizations_org_id'), table_name='spend_authorizations')
    op.drop_index(op.f('ix_spend_authorizations_card_id'), table_name='spend_authorizations')
    op.drop_table('spend_authorizations')
    op.drop_index(op.f('ix_cards_stripe_card_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_org_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_cardholder_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_spend_budgets_org_id'), table_name='spend_budgets')
    op.drop_index(op.f('ix_spend_budgets_merchant'), table_name='spend_budgets')
    op.drop_index(op.f('ix_spend_budgets_mcc'), table_name='spend_budgets')
    op.drop_index(op.f('ix_spend_budgets_category'), table_name='spend_budgets')
    op.drop_table('spend_budgets')
    op.drop_index(op.f('ix_entitlements_stripe_subscription_id'), table_name='entitlements')
    op.drop_index(op.f('ix_entitlements_org_id'), table_name='entitlements')
    op.drop_table('entitlements')
    op.drop_index(op.f('ix_cardholders_stripe_cardholder_id'), table_name='cardholders')
    op.drop_index(op.f('ix_cardholders_org_id'), table_name='cardholders')
    op.drop_table('cardholders')
    # ### end Alembic commands ###
