"""workflow job queue

Revision ID: bce9faaba33b
Revises: f28c812fca98
Create Date: 2026-06-19 16:03:11.252211
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bce9faaba33b'
down_revision: str | None = 'f28c812fca98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_jobs',
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_jobs_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_jobs')),
    sa.UniqueConstraint('run_id', name=op.f('uq_workflow_jobs_run_id'))
    )
    op.create_index('ix_workflow_jobs_claimable', 'workflow_jobs', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_jobs_claimable', table_name='workflow_jobs')
    op.drop_table('workflow_jobs')
    # ### end Alembic commands ###
