"""initial schema

Revision ID: f28c812fca98
Revises: 
Create Date: 2026-06-19 14:38:07.288248
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = 'f28c812fca98'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required extensions must exist before any vector column / trigram index is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('uei', sa.String(length=32), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('external_auth_id', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_external_auth_id'), 'users', ['external_auth_id'], unique=True)
    op.create_table('audit_events',
    sa.Column('filing_id', sa.UUID(), nullable=True),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('step_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_audit_events_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_org_id'), 'audit_events', ['org_id'], unique=False)
    op.create_index('ix_audit_events_org_occurred', 'audit_events', ['org_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_run', 'audit_events', ['run_id'], unique=False)
    op.create_table('company_profiles',
    sa.Column('website_url', sa.String(length=2048), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('naics_guesses', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('funding_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('target_customers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('user_overrides', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('capability_statement', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_company_profiles_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company_profiles')),
    sa.UniqueConstraint('org_id', name=op.f('uq_company_profiles_org_id'))
    )
    op.create_index(op.f('ix_company_profiles_org_id'), 'company_profiles', ['org_id'], unique=False)
    op.create_table('customer_feedback',
    sa.Column('rating', sa.Numeric(precision=2, scale=0), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_customer_feedback_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_feedback'))
    )
    op.create_index(op.f('ix_customer_feedback_org_id'), 'customer_feedback', ['org_id'], unique=False)
    op.create_table('documents',
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_uri', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('source_kind', sa.String(length=32), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_documents_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('org_id', 'content_hash', name=op.f('uq_documents_org_id'))
    )
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_table('org_members',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_org_members_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_org_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_org_members')),
    sa.UniqueConstraint('org_id', 'user_id', name=op.f('uq_org_members_org_id'))
    )
    op.create_index(op.f('ix_org_members_org_id'), 'org_members', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_members_user_id'), 'org_members', ['user_id'], unique=False)
    op.create_table('revenue_records',
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('charged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_revenue_records_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revenue_records')),
    sa.UniqueConstraint('external_id', name=op.f('uq_revenue_records_external_id'))
    )
    op.create_index(op.f('ix_revenue_records_org_id'), 'revenue_records', ['org_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('product', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_subscriptions_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_external_id'), 'subscriptions', ['external_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('locator', sa.String(length=255), nullable=True),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_document_chunks_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'ordinal', name=op.f('uq_document_chunks_document_id'))
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_document_chunks_org_id'), 'document_chunks', ['org_id'], unique=False)
    op.create_table('sources',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('snapshot_uri', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_sources_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_sources_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_document_id'), 'sources', ['document_id'], unique=False)
    op.create_index(op.f('ix_sources_org_id'), 'sources', ['org_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('document_chunk_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_chunk_id'], ['document_chunks.id'], name=op.f('fk_evidence_items_document_chunk_id_document_chunks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_evidence_items_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidence_items_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items'))
    )
    op.create_index(op.f('ix_evidence_items_document_chunk_id'), 'evidence_items', ['document_chunk_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_org_id'), 'evidence_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_source_id'), 'evidence_items', ['source_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('sponsor', sa.String(length=512), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('fit_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('decision_hint', sa.String(length=32), nullable=True),
    sa.Column('fit_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_opportunities_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_opportunities_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_external_id'), 'opportunities', ['external_id'], unique=False)
    op.create_index(op.f('ix_opportunities_kind'), 'opportunities', ['kind'], unique=False)
    op.create_index(op.f('ix_opportunities_org_id'), 'opportunities', ['org_id'], unique=False)
    op.create_index(op.f('ix_opportunities_source_id'), 'opportunities', ['source_id'], unique=False)
    op.create_table('filings',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_filings_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_filings_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_filings_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filings'))
    )
    op.create_index(op.f('ix_filings_opportunity_id'), 'filings', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_filings_org_id'), 'filings', ['org_id'], unique=False)
    op.create_index(op.f('ix_filings_status'), 'filings', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.String(length=16), nullable=False),
    sa.Column('approver_user_id', sa.UUID(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['users.id'], name=op.f('fk_approvals_approver_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_approvals_filing_id_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_approvals_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_filing_id'), 'approvals', ['filing_id'], unique=False)
    op.create_index(op.f('ix_approvals_org_id'), 'approvals', ['org_id'], unique=False)
    op.create_table('filing_requirements',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('locator', sa.String(length=255), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_filing_requirements_filing_id_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_filing_requirements_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_filing_requirements_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_filing_requirements'))
    )
    op.create_index(op.f('ix_filing_requirements_filing_id'), 'filing_requirements', ['filing_id'], unique=False)
    op.create_index(op.f('ix_filing_requirements_org_id'), 'filing_requirements', ['org_id'], unique=False)
    op.create_table('generated_documents',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('export_uri', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citation_validated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_generated_documents_filing_id_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_generated_documents_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_documents')),
    sa.UniqueConstraint('filing_id', 'type', 'version', name=op.f('uq_generated_documents_filing_id'))
    )
    op.create_index(op.f('ix_generated_documents_filing_id'), 'generated_documents', ['filing_id'], unique=False)
    op.create_index(op.f('ix_generated_documents_org_id'), 'generated_documents', ['org_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_recommendations_filing_id_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_recommendations_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations')),
    sa.UniqueConstraint('filing_id', name=op.f('uq_recommendations_filing_id'))
    )
    op.create_index(op.f('ix_recommendations_filing_id'), 'recommendations', ['filing_id'], unique=False)
    op.create_index(op.f('ix_recommendations_org_id'), 'recommendations', ['org_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('filing_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('partial_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('time_saved_minutes', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_workflow_runs_filing_id_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflow_runs_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_runs'))
    )
    op.create_index(op.f('ix_workflow_runs_filing_id'), 'workflow_runs', ['filing_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_org_id'), 'workflow_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    op.create_table('evidence_matches',
    sa.Column('filing_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('evidence_item_id', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_item_id'], ['evidence_items.id'], name=op.f('fk_evidence_matches_evidence_item_id_evidence_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['filing_id'], ['filings.id'], name=op.f('fk_evidence_matches_filing_id_filings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_evidence_matches_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['filing_requirements.id'], name=op.f('fk_evidence_matches_requirement_id_filing_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_matches'))
    )
    op.create_index(op.f('ix_evidence_matches_filing_id'), 'evidence_matches', ['filing_id'], unique=False)
    op.create_index(op.f('ix_evidence_matches_org_id'), 'evidence_matches', ['org_id'], unique=False)
    op.create_index(op.f('ix_evidence_matches_requirement_id'), 'evidence_matches', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_evidence_matches_status'), 'evidence_matches', ['status'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_workflow_steps_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], name=op.f('fk_workflow_steps_run_id_workflow_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_steps')),
    sa.UniqueConstraint('run_id', 'name', name=op.f('uq_workflow_steps_run_id'))
    )
    op.create_index(op.f('ix_workflow_steps_org_id'), 'workflow_steps', ['org_id'], unique=False)
    op.create_index(op.f('ix_workflow_steps_run_id'), 'workflow_steps', ['run_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('agent_name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_agent_runs_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], name=op.f('fk_agent_runs_step_id_workflow_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_org_id'), 'agent_runs', ['org_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_step_id'), 'agent_runs', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_step_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_org_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_workflow_steps_run_id'), table_name='workflow_steps')
    op.drop_index(op.f('ix_workflow_steps_org_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_evidence_matches_status'), table_name='evidence_matches')
    op.drop_index(op.f('ix_evidence_matches_requirement_id'), table_name='evidence_matches')
    op.drop_index(op.f('ix_evidence_matches_org_id'), table_name='evidence_matches')
    op.drop_index(op.f('ix_evidence_matches_filing_id'), table_name='evidence_matches')
    op.drop_table('evidence_matches')
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_org_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_filing_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_recommendations_org_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_filing_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_generated_documents_org_id'), table_name='generated_documents')
    op.drop_index(op.f('ix_generated_documents_filing_id'), table_name='generated_documents')
    op.drop_table('generated_documents')
    op.drop_index(op.f('ix_filing_requirements_org_id'), table_name='filing_requirements')
    op.drop_index(op.f('ix_filing_requirements_filing_id'), table_name='filing_requirements')
    op.drop_table('filing_requirements')
    op.drop_index(op.f('ix_approvals_org_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_filing_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_filings_status'), table_name='filings')
    op.drop_index(op.f('ix_filings_org_id'), table_name='filings')
    op.drop_index(op.f('ix_filings_opportunity_id'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_opportunities_source_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_org_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_kind'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_external_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_evidence_items_source_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_org_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_document_chunk_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_sources_org_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_document_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_document_chunks_org_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_external_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_revenue_records_org_id'), table_name='revenue_records')
    op.drop_table('revenue_records')
    op.drop_index(op.f('ix_org_members_user_id'), table_name='org_members')
    op.drop_index(op.f('ix_org_members_org_id'), table_name='org_members')
    op.drop_table('org_members')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_customer_feedback_org_id'), table_name='customer_feedback')
    op.drop_table('customer_feedback')
    op.drop_index(op.f('ix_company_profiles_org_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_index('ix_audit_events_run', table_name='audit_events')
    op.drop_index('ix_audit_events_org_occurred', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_org_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_occurred_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_external_auth_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
